name: ci

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      gph-db:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: gph
        ports:
          - 5435:5432

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test all features
        run: cargo test --all-features
        env:
          DATABASE_URL: postgresql://localhost:5435/gph?user=root&password=pass
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}